require("./PDP-EL-Carousel")
require("./PDP-EL-SeeMore")
require("./PDP-HB-Carousel")
require("./PLP-HB-BrandCategory-Carousel")
require("./PLP-HB-Brand-Carousel.js")
require("./PLP-HB-Category-Carousel.js")
require("./PDP-HB-SeeMore.js")
setTimeout(function () {
	require("./PLP-EL-BrandCategory-Carousel")
	require("./PLP-EL-Brand-Carousel")
	require("./PLP-EL-Category-Carousel.js")
	require("./PLP-FA-BrandCategory-Men-Carousel")
	require("./PLP-FA-BrandCategory-Women-Carousel")
	require("./PLP-FA-Brand-Carousel")
	require("./PLP-FA-Category-Carousel")
	require("./Coupons-Store-Carousel")
	require("./PDP-PLP-SeeMore")
},40000);